### PR TITLE
Elizabeth update  2

### PR DESCRIPTION
**Pull request by Felipe-Arrazola**
## 🎯 Objective

_Note why you're making this change and any relevant issues_

## 🛠️ Changes made

_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Review by Felipe-Arrazola — COMMENTED** [review]
I agree, we need more time for this amount of meat

**Review by Felipe-Arrazola — COMMENTED** [review]
Looks good to me

**Review by gebarn — APPROVED** [review]
Totally good with these changes.

**Comment by Eliz226** [comment]
hi @Felipe-Arrazola thanks for creating a pull request for me commit! Just want to make sure next time we would raise pull request for ourselves because I shouldn't be the approver, and can't add you as an approver too.

**Pull request merged**
